name: Upload to Databricks DBFS

on:
  push:
    branches: ["develop"]   # pipeline will run when you push to 'develop'

jobs:
  upload-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Databricks
        run: |
          pip install databricks

      - name: Authenticate with Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks auth login --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN" --profile "ci-profile"

      - name: Upload code to DBFS
        run: |
          databricks fs mkdirs dbfs:/FileStore/code/portfolio --profile "ci-profile"
          databricks fs cp --overwrite --recursive databricks/src/ dbfs:/FileStore/code/portfolio/src/ --profile "ci-profile"
      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now --job-id 12345 --profile "ci-profile"